// AUTO-GENERATED by mocks/generate.ts. Do not edit by hand.
// Re-run `npm run generate-mocks` to refresh.

/* eslint-disable */
import fetchPoxInfo__default from './data/fetchPoxInfo/default.json';
import fetchPoxInfo__d_30 from './data/fetchPoxInfo/d-30.json';
import fetchPoxInfo__d_7 from './data/fetchPoxInfo/d-7.json';
import fetchPoxInfo__d0 from './data/fetchPoxInfo/d0.json';
import fetchPoxInfo__d90 from './data/fetchPoxInfo/d90.json';
import fetchPoxInfo__d182 from './data/fetchPoxInfo/d182.json';
import fetchPoxInfo__d183 from './data/fetchPoxInfo/d183.json';
import fetchAccountStatus__default from './data/fetchAccountStatus/default.json';
import fetchAccountStatus__d0 from './data/fetchAccountStatus/d0.json';
import fetchAccountStatus__d90 from './data/fetchAccountStatus/d90.json';
import fetchAccountStatus__d182 from './data/fetchAccountStatus/d182.json';
import fetchAccountStatus__d183 from './data/fetchAccountStatus/d183.json';
import fetchStakerInfo__default from './data/fetchStakerInfo/default.json';
import fetchStakerInfo__d_7 from './data/fetchStakerInfo/d-7.json';
import fetchStakerInfo__d0 from './data/fetchStakerInfo/d0.json';
import fetchStakerInfo__d90 from './data/fetchStakerInfo/d90.json';
import fetchStakerInfo__d182 from './data/fetchStakerInfo/d182.json';
import fetchStakerInfo__d183 from './data/fetchStakerInfo/d183.json';
import fetchBondMembership__default from './data/fetchBondMembership/default.json';
import fetchBondMembership__d_7 from './data/fetchBondMembership/d-7.json';
import fetchBondMembership__d0 from './data/fetchBondMembership/d0.json';
import fetchBondMembership__d14 from './data/fetchBondMembership/d14.json';
import fetchBondMembership__d90 from './data/fetchBondMembership/d90.json';
import fetchBondMembership__d172 from './data/fetchBondMembership/d172.json';
import fetchBondMembership__d177 from './data/fetchBondMembership/d177.json';
import fetchBondMembership__d182 from './data/fetchBondMembership/d182.json';
import fetchBondMembership__d183 from './data/fetchBondMembership/d183.json';
import fetchAllowanceContractCallers__default from './data/fetchAllowanceContractCallers/default.json';
import fetchAllowanceContractCallers__d0 from './data/fetchAllowanceContractCallers/d0.json';
import fetchAllowanceContractCallers__d90 from './data/fetchAllowanceContractCallers/d90.json';
import fetchAllowanceContractCallers__d182 from './data/fetchAllowanceContractCallers/d182.json';
import fetchAllowanceContractCallers__d183 from './data/fetchAllowanceContractCallers/d183.json';
import fetchBond__default from './data/fetchBond/default.json';
import fetchBond__d_30 from './data/fetchBond/d-30.json';
import fetchBond__d_7 from './data/fetchBond/d-7.json';
import fetchBond__d0 from './data/fetchBond/d0.json';
import fetchBond__d90 from './data/fetchBond/d90.json';
import fetchBond__d182 from './data/fetchBond/d182.json';
import fetchBond__d183 from './data/fetchBond/d183.json';
import fetchProtocolBond__default from './data/fetchProtocolBond/default.json';
import fetchProtocolBond__d_30 from './data/fetchProtocolBond/d-30.json';
import fetchProtocolBond__d_7 from './data/fetchProtocolBond/d-7.json';
import fetchProtocolBond__d0 from './data/fetchProtocolBond/d0.json';
import fetchProtocolBond__d90 from './data/fetchProtocolBond/d90.json';
import fetchProtocolBond__d182 from './data/fetchProtocolBond/d182.json';
import fetchProtocolBond__d183 from './data/fetchProtocolBond/d183.json';
import fetchBondAllowance__default from './data/fetchBondAllowance/default.json';
import fetchBondAllowance__d_7 from './data/fetchBondAllowance/d-7.json';
import fetchBondAllowance__d0 from './data/fetchBondAllowance/d0.json';
import fetchBondAllowance__d90 from './data/fetchBondAllowance/d90.json';
import fetchBondAllowance__d182 from './data/fetchBondAllowance/d182.json';
import fetchTotalSbtcStakedForBond__default from './data/fetchTotalSbtcStakedForBond/default.json';
import fetchTotalSbtcStakedForBond__d_7 from './data/fetchTotalSbtcStakedForBond/d-7.json';
import fetchTotalSbtcStakedForBond__d0 from './data/fetchTotalSbtcStakedForBond/d0.json';
import fetchTotalSbtcStakedForBond__d90 from './data/fetchTotalSbtcStakedForBond/d90.json';
import fetchTotalSbtcStakedForBond__d182 from './data/fetchTotalSbtcStakedForBond/d182.json';
import fetchTotalSbtcStakedForBond__d183 from './data/fetchTotalSbtcStakedForBond/d183.json';
import fetchTotalSharesStakedForCycle__default from './data/fetchTotalSharesStakedForCycle/default.json';
import fetchTotalSharesStakedForCycle__d_7 from './data/fetchTotalSharesStakedForCycle/d-7.json';
import fetchTotalSharesStakedForCycle__d0 from './data/fetchTotalSharesStakedForCycle/d0.json';
import fetchTotalSharesStakedForCycle__d14 from './data/fetchTotalSharesStakedForCycle/d14.json';
import fetchTotalSharesStakedForCycle__d90 from './data/fetchTotalSharesStakedForCycle/d90.json';
import fetchTotalSharesStakedForCycle__d172 from './data/fetchTotalSharesStakedForCycle/d172.json';
import fetchTotalSharesStakedForCycle__d183 from './data/fetchTotalSharesStakedForCycle/d183.json';
import fetchTotalSbtcStaked__default from './data/fetchTotalSbtcStaked/default.json';
import fetchTotalSbtcStaked__d_30 from './data/fetchTotalSbtcStaked/d-30.json';
import fetchTotalSbtcStaked__d0 from './data/fetchTotalSbtcStaked/d0.json';
import fetchTotalSbtcStaked__d90 from './data/fetchTotalSbtcStaked/d90.json';
import fetchTotalSbtcStaked__d183 from './data/fetchTotalSbtcStaked/d183.json';
import fetchTotalUstxStacked__default from './data/fetchTotalUstxStacked/default.json';
import fetchTotalUstxStacked__d0 from './data/fetchTotalUstxStacked/d0.json';
import fetchTotalUstxStacked__d90 from './data/fetchTotalUstxStacked/d90.json';
import fetchTotalUstxStacked__d182 from './data/fetchTotalUstxStacked/d182.json';
import fetchBondL1UnlockHeight__default from './data/fetchBondL1UnlockHeight/default.json';
import fetchBondL1UnlockHeight__d_30 from './data/fetchBondL1UnlockHeight/d-30.json';
import fetchBondL1UnlockHeight__d0 from './data/fetchBondL1UnlockHeight/d0.json';
import fetchBondL1UnlockHeight__d90 from './data/fetchBondL1UnlockHeight/d90.json';
import fetchBondL1UnlockHeight__d182 from './data/fetchBondL1UnlockHeight/d182.json';
import fetchStakerSharesStakedByBond__default from './data/fetchStakerSharesStakedByBond/default.json';
import fetchStakerSharesStakedByBond__d0 from './data/fetchStakerSharesStakedByBond/d0.json';
import fetchStakerSharesStakedByBond__d90 from './data/fetchStakerSharesStakedByBond/d90.json';
import fetchStakerSharesStakedByBond__d182 from './data/fetchStakerSharesStakedByBond/d182.json';
import fetchStakerSharesStakedByBond__d183 from './data/fetchStakerSharesStakedByBond/d183.json';
import fetchStakerSharesStakedByCycle__default from './data/fetchStakerSharesStakedByCycle/default.json';
import fetchStakerSharesStakedByCycle__d0 from './data/fetchStakerSharesStakedByCycle/d0.json';
import fetchStakerSharesStakedByCycle__d90 from './data/fetchStakerSharesStakedByCycle/d90.json';
import fetchStakerSharesStakedByCycle__d182 from './data/fetchStakerSharesStakedByCycle/d182.json';
import fetchStakerSharesStakedByCycle__d183 from './data/fetchStakerSharesStakedByCycle/d183.json';
import fetchStakerSharesStakedForCycle__default from './data/fetchStakerSharesStakedForCycle/default.json';
import fetchStakerSharesStakedForCycle__d0 from './data/fetchStakerSharesStakedForCycle/d0.json';
import fetchStakerSharesStakedForCycle__d90 from './data/fetchStakerSharesStakedForCycle/d90.json';
import fetchStakerSharesStakedForCycle__d182 from './data/fetchStakerSharesStakedForCycle/d182.json';
import fetchSignerSharesStakedByBond__default from './data/fetchSignerSharesStakedByBond/default.json';
import fetchSignerSharesStakedByBond__d0 from './data/fetchSignerSharesStakedByBond/d0.json';
import fetchSignerSharesStakedByBond__d90 from './data/fetchSignerSharesStakedByBond/d90.json';
import fetchSignerSharesStakedByBond__d182 from './data/fetchSignerSharesStakedByBond/d182.json';
import fetchSignerSharesStakedByBond__d183 from './data/fetchSignerSharesStakedByBond/d183.json';
import fetchSignerSharesStakedByCycle__default from './data/fetchSignerSharesStakedByCycle/default.json';
import fetchSignerSharesStakedByCycle__d0 from './data/fetchSignerSharesStakedByCycle/d0.json';
import fetchSignerSharesStakedByCycle__d90 from './data/fetchSignerSharesStakedByCycle/d90.json';
import fetchSignerSharesStakedByCycle__d182 from './data/fetchSignerSharesStakedByCycle/d182.json';
import fetchEarned__default from './data/fetchEarned/default.json';
import fetchEarned__d14 from './data/fetchEarned/d14.json';
import fetchEarned__d90 from './data/fetchEarned/d90.json';
import fetchEarned__d182 from './data/fetchEarned/d182.json';
import fetchEarned__d183 from './data/fetchEarned/d183.json';
import fetchEarnedByBond__default from './data/fetchEarnedByBond/default.json';
import fetchEarnedByBond__d14 from './data/fetchEarnedByBond/d14.json';
import fetchEarnedByBond__d90 from './data/fetchEarnedByBond/d90.json';
import fetchEarnedByBond__d182 from './data/fetchEarnedByBond/d182.json';
import fetchEarnedByBond__d183 from './data/fetchEarnedByBond/d183.json';
import fetchEarnedByCycle__default from './data/fetchEarnedByCycle/default.json';
import fetchEarnedByCycle__d14 from './data/fetchEarnedByCycle/d14.json';
import fetchEarnedByCycle__d90 from './data/fetchEarnedByCycle/d90.json';
import fetchEarnedByCycle__d182 from './data/fetchEarnedByCycle/d182.json';
import fetchEarnedByCycle__d183 from './data/fetchEarnedByCycle/d183.json';
import fetchSignerUnclaimedRewards__default from './data/fetchSignerUnclaimedRewards/default.json';
import fetchSignerUnclaimedRewards__d14 from './data/fetchSignerUnclaimedRewards/d14.json';
import fetchSignerUnclaimedRewards__d90 from './data/fetchSignerUnclaimedRewards/d90.json';
import fetchSignerUnclaimedRewards__d182 from './data/fetchSignerUnclaimedRewards/d182.json';
import fetchSignerUnclaimedRewards__d183 from './data/fetchSignerUnclaimedRewards/d183.json';
import fetchSignerRewardsPerTokenSettled__default from './data/fetchSignerRewardsPerTokenSettled/default.json';
import fetchSignerRewardsPerTokenSettled__d14 from './data/fetchSignerRewardsPerTokenSettled/d14.json';
import fetchSignerRewardsPerTokenSettled__d90 from './data/fetchSignerRewardsPerTokenSettled/d90.json';
import fetchSignerRewardsPerTokenSettled__d182 from './data/fetchSignerRewardsPerTokenSettled/d182.json';
import fetchSignerRewardsPerTokenSettledByBond__default from './data/fetchSignerRewardsPerTokenSettledByBond/default.json';
import fetchSignerRewardsPerTokenSettledByBond__d14 from './data/fetchSignerRewardsPerTokenSettledByBond/d14.json';
import fetchSignerRewardsPerTokenSettledByBond__d90 from './data/fetchSignerRewardsPerTokenSettledByBond/d90.json';
import fetchSignerRewardsPerTokenSettledByBond__d182 from './data/fetchSignerRewardsPerTokenSettledByBond/d182.json';
import fetchSignerRewardsPerTokenSettledByCycle__default from './data/fetchSignerRewardsPerTokenSettledByCycle/default.json';
import fetchSignerRewardsPerTokenSettledByCycle__d14 from './data/fetchSignerRewardsPerTokenSettledByCycle/d14.json';
import fetchSignerRewardsPerTokenSettledByCycle__d90 from './data/fetchSignerRewardsPerTokenSettledByCycle/d90.json';
import fetchSignerRewardsPerTokenSettledByCycle__d182 from './data/fetchSignerRewardsPerTokenSettledByCycle/d182.json';
import fetchSignerInfo__default from './data/fetchSignerInfo/default.json';
import fetchSignerInfo__d_30 from './data/fetchSignerInfo/d-30.json';
import fetchSignerInfo__d0 from './data/fetchSignerInfo/d0.json';
import fetchSignerInfo__d90 from './data/fetchSignerInfo/d90.json';
import fetchSignerInfo__d182 from './data/fetchSignerInfo/d182.json';
import fetchVerifySignerKeyGrant__default from './data/fetchVerifySignerKeyGrant/default.json';
import fetchVerifySignerKeyGrant__d_30 from './data/fetchVerifySignerKeyGrant/d-30.json';
import fetchVerifySignerKeyGrant__d0 from './data/fetchVerifySignerKeyGrant/d0.json';
import fetchVerifySignerKeyGrant__d90 from './data/fetchVerifySignerKeyGrant/d90.json';
import fetchVerifySignerKeyGrant__d182 from './data/fetchVerifySignerKeyGrant/d182.json';
import fetchSignerGrantMessageHash__default from './data/fetchSignerGrantMessageHash/default.json';
import mockListBonds__default from './data/mockListBonds/default.json';
import mockListBonds__d_30 from './data/mockListBonds/d-30.json';
import mockListBonds__d0 from './data/mockListBonds/d0.json';
import mockListBonds__d90 from './data/mockListBonds/d90.json';
import mockListBonds__d177 from './data/mockListBonds/d177.json';
import mockListBonds__d183 from './data/mockListBonds/d183.json';
import mockGetBond__default from './data/mockGetBond/default.json';
import mockGetBond__d_30 from './data/mockGetBond/d-30.json';
import mockGetBond__d0 from './data/mockGetBond/d0.json';
import mockGetBond__d90 from './data/mockGetBond/d90.json';
import mockGetBond__d177 from './data/mockGetBond/d177.json';
import mockGetBond__d183 from './data/mockGetBond/d183.json';
import mockListBondAllowlist__default from './data/mockListBondAllowlist/default.json';
import mockListBondAllowlist__d_7 from './data/mockListBondAllowlist/d-7.json';
import mockListBondAllowlist__d90 from './data/mockListBondAllowlist/d90.json';
import mockGetBondAllowlistEntry__default from './data/mockGetBondAllowlistEntry/default.json';
import mockGetBondAllowlistEntry__d_7 from './data/mockGetBondAllowlistEntry/d-7.json';
import mockGetBondAllowlistEntry__d0 from './data/mockGetBondAllowlistEntry/d0.json';
import mockGetBondAllowlistEntry__d90 from './data/mockGetBondAllowlistEntry/d90.json';
import mockListBondRegistrations__default from './data/mockListBondRegistrations/default.json';
import mockListBondRegistrations__d_7 from './data/mockListBondRegistrations/d-7.json';
import mockListBondRegistrations__d0 from './data/mockListBondRegistrations/d0.json';
import mockListBondRegistrations__d90 from './data/mockListBondRegistrations/d90.json';
import mockListBondRegistrations__d172 from './data/mockListBondRegistrations/d172.json';
import mockListBondRegistrations__d183 from './data/mockListBondRegistrations/d183.json';
import mockGetBondRegistration__default from './data/mockGetBondRegistration/default.json';
import mockGetBondRegistration__d_7 from './data/mockGetBondRegistration/d-7.json';
import mockGetBondRegistration__d0 from './data/mockGetBondRegistration/d0.json';
import mockGetBondRegistration__d90 from './data/mockGetBondRegistration/d90.json';
import mockGetBondRegistration__d172 from './data/mockGetBondRegistration/d172.json';
import mockGetBondRegistration__d183 from './data/mockGetBondRegistration/d183.json';
import mockListCycles__default from './data/mockListCycles/default.json';
import mockListCycles__d0 from './data/mockListCycles/d0.json';
import mockListCycles__d90 from './data/mockListCycles/d90.json';
import mockGetCycle__default from './data/mockGetCycle/default.json';
import mockGetCycle__d0 from './data/mockGetCycle/d0.json';
import mockGetCycle__d90 from './data/mockGetCycle/d90.json';
import mockGetCycle__d182 from './data/mockGetCycle/d182.json';
import mockListCycleSigners__default from './data/mockListCycleSigners/default.json';
import mockListCycleSigners__d0 from './data/mockListCycleSigners/d0.json';
import mockListCycleSigners__d90 from './data/mockListCycleSigners/d90.json';
import mockListSignerStakers__default from './data/mockListSignerStakers/default.json';
import mockListSignerStakers__d0 from './data/mockListSignerStakers/d0.json';
import mockListSignerStakers__d90 from './data/mockListSignerStakers/d90.json';
import mockListCycleStakers__default from './data/mockListCycleStakers/default.json';
import mockListCycleStakers__d0 from './data/mockListCycleStakers/d0.json';
import mockListCycleStakers__d90 from './data/mockListCycleStakers/d90.json';

export const fetchPoxInfo_FIXTURES: Record<string, unknown> = {
  "default": fetchPoxInfo__default,
  "d-30": fetchPoxInfo__d_30,
  "d-7": fetchPoxInfo__d_7,
  "d0": fetchPoxInfo__d0,
  "d90": fetchPoxInfo__d90,
  "d182": fetchPoxInfo__d182,
  "d183": fetchPoxInfo__d183,
};

export const fetchPoxInfo_DAYS: string[] = ["default", "d-30", "d-7", "d0", "d90", "d182", "d183"];

export const fetchAccountStatus_FIXTURES: Record<string, unknown> = {
  "default": fetchAccountStatus__default,
  "d0": fetchAccountStatus__d0,
  "d90": fetchAccountStatus__d90,
  "d182": fetchAccountStatus__d182,
  "d183": fetchAccountStatus__d183,
};

export const fetchAccountStatus_DAYS: string[] = ["default", "d0", "d90", "d182", "d183"];

export const fetchStakerInfo_FIXTURES: Record<string, unknown> = {
  "default": fetchStakerInfo__default,
  "d-7": fetchStakerInfo__d_7,
  "d0": fetchStakerInfo__d0,
  "d90": fetchStakerInfo__d90,
  "d182": fetchStakerInfo__d182,
  "d183": fetchStakerInfo__d183,
};

export const fetchStakerInfo_DAYS: string[] = ["default", "d-7", "d0", "d90", "d182", "d183"];

export const fetchBondMembership_FIXTURES: Record<string, unknown> = {
  "default": fetchBondMembership__default,
  "d-7": fetchBondMembership__d_7,
  "d0": fetchBondMembership__d0,
  "d14": fetchBondMembership__d14,
  "d90": fetchBondMembership__d90,
  "d172": fetchBondMembership__d172,
  "d177": fetchBondMembership__d177,
  "d182": fetchBondMembership__d182,
  "d183": fetchBondMembership__d183,
};

export const fetchBondMembership_DAYS: string[] = ["default", "d-7", "d0", "d14", "d90", "d172", "d177", "d182", "d183"];

export const fetchAllowanceContractCallers_FIXTURES: Record<string, unknown> = {
  "default": fetchAllowanceContractCallers__default,
  "d0": fetchAllowanceContractCallers__d0,
  "d90": fetchAllowanceContractCallers__d90,
  "d182": fetchAllowanceContractCallers__d182,
  "d183": fetchAllowanceContractCallers__d183,
};

export const fetchAllowanceContractCallers_DAYS: string[] = ["default", "d0", "d90", "d182", "d183"];

export const fetchBond_FIXTURES: Record<string, unknown> = {
  "default": fetchBond__default,
  "d-30": fetchBond__d_30,
  "d-7": fetchBond__d_7,
  "d0": fetchBond__d0,
  "d90": fetchBond__d90,
  "d182": fetchBond__d182,
  "d183": fetchBond__d183,
};

export const fetchBond_DAYS: string[] = ["default", "d-30", "d-7", "d0", "d90", "d182", "d183"];

export const fetchProtocolBond_FIXTURES: Record<string, unknown> = {
  "default": fetchProtocolBond__default,
  "d-30": fetchProtocolBond__d_30,
  "d-7": fetchProtocolBond__d_7,
  "d0": fetchProtocolBond__d0,
  "d90": fetchProtocolBond__d90,
  "d182": fetchProtocolBond__d182,
  "d183": fetchProtocolBond__d183,
};

export const fetchProtocolBond_DAYS: string[] = ["default", "d-30", "d-7", "d0", "d90", "d182", "d183"];

export const fetchBondAllowance_FIXTURES: Record<string, unknown> = {
  "default": fetchBondAllowance__default,
  "d-7": fetchBondAllowance__d_7,
  "d0": fetchBondAllowance__d0,
  "d90": fetchBondAllowance__d90,
  "d182": fetchBondAllowance__d182,
};

export const fetchBondAllowance_DAYS: string[] = ["default", "d-7", "d0", "d90", "d182"];

export const fetchTotalSbtcStakedForBond_FIXTURES: Record<string, unknown> = {
  "default": fetchTotalSbtcStakedForBond__default,
  "d-7": fetchTotalSbtcStakedForBond__d_7,
  "d0": fetchTotalSbtcStakedForBond__d0,
  "d90": fetchTotalSbtcStakedForBond__d90,
  "d182": fetchTotalSbtcStakedForBond__d182,
  "d183": fetchTotalSbtcStakedForBond__d183,
};

export const fetchTotalSbtcStakedForBond_DAYS: string[] = ["default", "d-7", "d0", "d90", "d182", "d183"];

export const fetchTotalSharesStakedForCycle_FIXTURES: Record<string, unknown> = {
  "default": fetchTotalSharesStakedForCycle__default,
  "d-7": fetchTotalSharesStakedForCycle__d_7,
  "d0": fetchTotalSharesStakedForCycle__d0,
  "d14": fetchTotalSharesStakedForCycle__d14,
  "d90": fetchTotalSharesStakedForCycle__d90,
  "d172": fetchTotalSharesStakedForCycle__d172,
  "d183": fetchTotalSharesStakedForCycle__d183,
};

export const fetchTotalSharesStakedForCycle_DAYS: string[] = ["default", "d-7", "d0", "d14", "d90", "d172", "d183"];

export const fetchTotalSbtcStaked_FIXTURES: Record<string, unknown> = {
  "default": fetchTotalSbtcStaked__default,
  "d-30": fetchTotalSbtcStaked__d_30,
  "d0": fetchTotalSbtcStaked__d0,
  "d90": fetchTotalSbtcStaked__d90,
  "d183": fetchTotalSbtcStaked__d183,
};

export const fetchTotalSbtcStaked_DAYS: string[] = ["default", "d-30", "d0", "d90", "d183"];

export const fetchTotalUstxStacked_FIXTURES: Record<string, unknown> = {
  "default": fetchTotalUstxStacked__default,
  "d0": fetchTotalUstxStacked__d0,
  "d90": fetchTotalUstxStacked__d90,
  "d182": fetchTotalUstxStacked__d182,
};

export const fetchTotalUstxStacked_DAYS: string[] = ["default", "d0", "d90", "d182"];

export const fetchBondL1UnlockHeight_FIXTURES: Record<string, unknown> = {
  "default": fetchBondL1UnlockHeight__default,
  "d-30": fetchBondL1UnlockHeight__d_30,
  "d0": fetchBondL1UnlockHeight__d0,
  "d90": fetchBondL1UnlockHeight__d90,
  "d182": fetchBondL1UnlockHeight__d182,
};

export const fetchBondL1UnlockHeight_DAYS: string[] = ["default", "d-30", "d0", "d90", "d182"];

export const fetchStakerSharesStakedByBond_FIXTURES: Record<string, unknown> = {
  "default": fetchStakerSharesStakedByBond__default,
  "d0": fetchStakerSharesStakedByBond__d0,
  "d90": fetchStakerSharesStakedByBond__d90,
  "d182": fetchStakerSharesStakedByBond__d182,
  "d183": fetchStakerSharesStakedByBond__d183,
};

export const fetchStakerSharesStakedByBond_DAYS: string[] = ["default", "d0", "d90", "d182", "d183"];

export const fetchStakerSharesStakedByCycle_FIXTURES: Record<string, unknown> = {
  "default": fetchStakerSharesStakedByCycle__default,
  "d0": fetchStakerSharesStakedByCycle__d0,
  "d90": fetchStakerSharesStakedByCycle__d90,
  "d182": fetchStakerSharesStakedByCycle__d182,
  "d183": fetchStakerSharesStakedByCycle__d183,
};

export const fetchStakerSharesStakedByCycle_DAYS: string[] = ["default", "d0", "d90", "d182", "d183"];

export const fetchStakerSharesStakedForCycle_FIXTURES: Record<string, unknown> = {
  "default": fetchStakerSharesStakedForCycle__default,
  "d0": fetchStakerSharesStakedForCycle__d0,
  "d90": fetchStakerSharesStakedForCycle__d90,
  "d182": fetchStakerSharesStakedForCycle__d182,
};

export const fetchStakerSharesStakedForCycle_DAYS: string[] = ["default", "d0", "d90", "d182"];

export const fetchSignerSharesStakedByBond_FIXTURES: Record<string, unknown> = {
  "default": fetchSignerSharesStakedByBond__default,
  "d0": fetchSignerSharesStakedByBond__d0,
  "d90": fetchSignerSharesStakedByBond__d90,
  "d182": fetchSignerSharesStakedByBond__d182,
  "d183": fetchSignerSharesStakedByBond__d183,
};

export const fetchSignerSharesStakedByBond_DAYS: string[] = ["default", "d0", "d90", "d182", "d183"];

export const fetchSignerSharesStakedByCycle_FIXTURES: Record<string, unknown> = {
  "default": fetchSignerSharesStakedByCycle__default,
  "d0": fetchSignerSharesStakedByCycle__d0,
  "d90": fetchSignerSharesStakedByCycle__d90,
  "d182": fetchSignerSharesStakedByCycle__d182,
};

export const fetchSignerSharesStakedByCycle_DAYS: string[] = ["default", "d0", "d90", "d182"];

export const fetchEarned_FIXTURES: Record<string, unknown> = {
  "default": fetchEarned__default,
  "d14": fetchEarned__d14,
  "d90": fetchEarned__d90,
  "d182": fetchEarned__d182,
  "d183": fetchEarned__d183,
};

export const fetchEarned_DAYS: string[] = ["default", "d14", "d90", "d182", "d183"];

export const fetchEarnedByBond_FIXTURES: Record<string, unknown> = {
  "default": fetchEarnedByBond__default,
  "d14": fetchEarnedByBond__d14,
  "d90": fetchEarnedByBond__d90,
  "d182": fetchEarnedByBond__d182,
  "d183": fetchEarnedByBond__d183,
};

export const fetchEarnedByBond_DAYS: string[] = ["default", "d14", "d90", "d182", "d183"];

export const fetchEarnedByCycle_FIXTURES: Record<string, unknown> = {
  "default": fetchEarnedByCycle__default,
  "d14": fetchEarnedByCycle__d14,
  "d90": fetchEarnedByCycle__d90,
  "d182": fetchEarnedByCycle__d182,
  "d183": fetchEarnedByCycle__d183,
};

export const fetchEarnedByCycle_DAYS: string[] = ["default", "d14", "d90", "d182", "d183"];

export const fetchSignerUnclaimedRewards_FIXTURES: Record<string, unknown> = {
  "default": fetchSignerUnclaimedRewards__default,
  "d14": fetchSignerUnclaimedRewards__d14,
  "d90": fetchSignerUnclaimedRewards__d90,
  "d182": fetchSignerUnclaimedRewards__d182,
  "d183": fetchSignerUnclaimedRewards__d183,
};

export const fetchSignerUnclaimedRewards_DAYS: string[] = ["default", "d14", "d90", "d182", "d183"];

export const fetchSignerRewardsPerTokenSettled_FIXTURES: Record<string, unknown> = {
  "default": fetchSignerRewardsPerTokenSettled__default,
  "d14": fetchSignerRewardsPerTokenSettled__d14,
  "d90": fetchSignerRewardsPerTokenSettled__d90,
  "d182": fetchSignerRewardsPerTokenSettled__d182,
};

export const fetchSignerRewardsPerTokenSettled_DAYS: string[] = ["default", "d14", "d90", "d182"];

export const fetchSignerRewardsPerTokenSettledByBond_FIXTURES: Record<string, unknown> = {
  "default": fetchSignerRewardsPerTokenSettledByBond__default,
  "d14": fetchSignerRewardsPerTokenSettledByBond__d14,
  "d90": fetchSignerRewardsPerTokenSettledByBond__d90,
  "d182": fetchSignerRewardsPerTokenSettledByBond__d182,
};

export const fetchSignerRewardsPerTokenSettledByBond_DAYS: string[] = ["default", "d14", "d90", "d182"];

export const fetchSignerRewardsPerTokenSettledByCycle_FIXTURES: Record<string, unknown> = {
  "default": fetchSignerRewardsPerTokenSettledByCycle__default,
  "d14": fetchSignerRewardsPerTokenSettledByCycle__d14,
  "d90": fetchSignerRewardsPerTokenSettledByCycle__d90,
  "d182": fetchSignerRewardsPerTokenSettledByCycle__d182,
};

export const fetchSignerRewardsPerTokenSettledByCycle_DAYS: string[] = ["default", "d14", "d90", "d182"];

export const fetchSignerInfo_FIXTURES: Record<string, unknown> = {
  "default": fetchSignerInfo__default,
  "d-30": fetchSignerInfo__d_30,
  "d0": fetchSignerInfo__d0,
  "d90": fetchSignerInfo__d90,
  "d182": fetchSignerInfo__d182,
};

export const fetchSignerInfo_DAYS: string[] = ["default", "d-30", "d0", "d90", "d182"];

export const fetchVerifySignerKeyGrant_FIXTURES: Record<string, unknown> = {
  "default": fetchVerifySignerKeyGrant__default,
  "d-30": fetchVerifySignerKeyGrant__d_30,
  "d0": fetchVerifySignerKeyGrant__d0,
  "d90": fetchVerifySignerKeyGrant__d90,
  "d182": fetchVerifySignerKeyGrant__d182,
};

export const fetchVerifySignerKeyGrant_DAYS: string[] = ["default", "d-30", "d0", "d90", "d182"];

export const fetchSignerGrantMessageHash_FIXTURES: Record<string, unknown> = {
  "default": fetchSignerGrantMessageHash__default,
};

export const fetchSignerGrantMessageHash_DAYS: string[] = ["default"];

export const mockListBonds_FIXTURES: Record<string, unknown> = {
  "default": mockListBonds__default,
  "d-30": mockListBonds__d_30,
  "d0": mockListBonds__d0,
  "d90": mockListBonds__d90,
  "d177": mockListBonds__d177,
  "d183": mockListBonds__d183,
};

export const mockListBonds_DAYS: string[] = ["default", "d-30", "d0", "d90", "d177", "d183"];

export const mockGetBond_FIXTURES: Record<string, unknown> = {
  "default": mockGetBond__default,
  "d-30": mockGetBond__d_30,
  "d0": mockGetBond__d0,
  "d90": mockGetBond__d90,
  "d177": mockGetBond__d177,
  "d183": mockGetBond__d183,
};

export const mockGetBond_DAYS: string[] = ["default", "d-30", "d0", "d90", "d177", "d183"];

export const mockListBondAllowlist_FIXTURES: Record<string, unknown> = {
  "default": mockListBondAllowlist__default,
  "d-7": mockListBondAllowlist__d_7,
  "d90": mockListBondAllowlist__d90,
};

export const mockListBondAllowlist_DAYS: string[] = ["default", "d-7", "d90"];

export const mockGetBondAllowlistEntry_FIXTURES: Record<string, unknown> = {
  "default": mockGetBondAllowlistEntry__default,
  "d-7": mockGetBondAllowlistEntry__d_7,
  "d0": mockGetBondAllowlistEntry__d0,
  "d90": mockGetBondAllowlistEntry__d90,
};

export const mockGetBondAllowlistEntry_DAYS: string[] = ["default", "d-7", "d0", "d90"];

export const mockListBondRegistrations_FIXTURES: Record<string, unknown> = {
  "default": mockListBondRegistrations__default,
  "d-7": mockListBondRegistrations__d_7,
  "d0": mockListBondRegistrations__d0,
  "d90": mockListBondRegistrations__d90,
  "d172": mockListBondRegistrations__d172,
  "d183": mockListBondRegistrations__d183,
};

export const mockListBondRegistrations_DAYS: string[] = ["default", "d-7", "d0", "d90", "d172", "d183"];

export const mockGetBondRegistration_FIXTURES: Record<string, unknown> = {
  "default": mockGetBondRegistration__default,
  "d-7": mockGetBondRegistration__d_7,
  "d0": mockGetBondRegistration__d0,
  "d90": mockGetBondRegistration__d90,
  "d172": mockGetBondRegistration__d172,
  "d183": mockGetBondRegistration__d183,
};

export const mockGetBondRegistration_DAYS: string[] = ["default", "d-7", "d0", "d90", "d172", "d183"];

export const mockListCycles_FIXTURES: Record<string, unknown> = {
  "default": mockListCycles__default,
  "d0": mockListCycles__d0,
  "d90": mockListCycles__d90,
};

export const mockListCycles_DAYS: string[] = ["default", "d0", "d90"];

export const mockGetCycle_FIXTURES: Record<string, unknown> = {
  "default": mockGetCycle__default,
  "d0": mockGetCycle__d0,
  "d90": mockGetCycle__d90,
  "d182": mockGetCycle__d182,
};

export const mockGetCycle_DAYS: string[] = ["default", "d0", "d90", "d182"];

export const mockListCycleSigners_FIXTURES: Record<string, unknown> = {
  "default": mockListCycleSigners__default,
  "d0": mockListCycleSigners__d0,
  "d90": mockListCycleSigners__d90,
};

export const mockListCycleSigners_DAYS: string[] = ["default", "d0", "d90"];

export const mockListSignerStakers_FIXTURES: Record<string, unknown> = {
  "default": mockListSignerStakers__default,
  "d0": mockListSignerStakers__d0,
  "d90": mockListSignerStakers__d90,
};

export const mockListSignerStakers_DAYS: string[] = ["default", "d0", "d90"];

export const mockListCycleStakers_FIXTURES: Record<string, unknown> = {
  "default": mockListCycleStakers__default,
  "d0": mockListCycleStakers__d0,
  "d90": mockListCycleStakers__d90,
};

export const mockListCycleStakers_DAYS: string[] = ["default", "d0", "d90"];
